const int rgb_modes_amount = 46;
const struct rgb_mode rgb_modes[] = 
		     {  { "Static Color",      0x01, 0x0,  6, INNER | OUTER | INNER_AND_OUTER | NOT_MOVING | BRIGHTNESS, 0 }, 
			{ "Breathing",         0x02, 0x0,  6, INNER | OUTER | INNER_AND_OUTER | NOT_MOVING | BRIGHTNESS | SPEED, 1 },
			{ "Rainbow Morph",     0x04, 0x0,  0, INNER | OUTER | INNER_AND_OUTER | BRIGHTNESS | SPEED, 2 },
			{ "Rainbow",           0x05, 0x0,  0, INNER | OUTER | BRIGHTNESS | SPEED | DIRECTION, 3 },
			{ "Breathing Rainbow", 0x06, 0x0,  0, OUTER | BRIGHTNESS | SPEED, 4 },
			{ "Meteor Rainbow",    0x08, 0x0,  0, INNER | OUTER | BRIGHTNESS | SPEED, 5 },
			{ "Color Cycle",       0x18, 0x0,  4, INNER | BRIGHTNESS | SPEED | DIRECTION, 6 },
			{ "Meteor", 	       0x19, 0x0,  4, INNER | OUTER | INNER_AND_OUTER | BRIGHTNESS | SPEED | DIRECTION, 7 },
			{ "Runway", 	       0x1a, 0x46, 2, INNER | OUTER | INNER_AND_OUTER | MERGE | BRIGHTNESS | SPEED | DIRECTION, 8 },
			{ "Mop Up", 	       0x1b, 0x0,  2, INNER | OUTER | SPEED | BRIGHTNESS, 9 },
			{ "Color Cycle",       0x1c, 0x0,  4, OUTER | BRIGHTNESS | SPEED | DIRECTION, 10 }, 
			{ "Lottery", 	       0x1d, 0x0,  2, INNER | OUTER  | BRIGHTNESS | SPEED | DIRECTION, 11 },
			{ "Wave", 	       0x1e, 0x0,  1, INNER | OUTER  | BRIGHTNESS | SPEED, 12 }, 
			{ "Spring", 	       0x1f, 0x0,  4, INNER | OUTER  | BRIGHTNESS | SPEED | DIRECTION, 13 },
			{ "Tail Chasing",      0x20, 0x0,  4, INNER | OUTER  | BRIGHTNESS | SPEED | DIRECTION, 14 },
			{ "Warning", 	       0x21, 0x0,  4, INNER | OUTER  | BRIGHTNESS | SPEED, 15 },
			{ "Voice", 	       0x22, 0x0,  4, INNER | OUTER  | BRIGHTNESS | SPEED | DIRECTION, 16 },
			{ "Mixing", 	       0x23, 0x0,  2, INNER | OUTER | BRIGHTNESS | SPEED, 17 },
			{ "Stack", 	       0x24, 0x0,  2, INNER | OUTER | BRIGHTNESS | SPEED | DIRECTION, 18 },
			{ "Tide", 	       0x25, 0x0,  4, INNER | OUTER | BRIGHTNESS | SPEED, 19 },
			{ "Scan", 	       0x26, 0x0,  1, INNER | OUTER | BRIGHTNESS | SPEED, 20 },
			{ "Pac-Man", 	       0x27, 0x0,  2, INNER | BRIGHTNESS | SPEED | DIRECTION, 21 },
			{ "Colorful City",     0x28, 0x0,  0, INNER | OUTER | BRIGHTNESS | SPEED, 22 },
			{ "Render", 	       0x29, 0x0,  4, INNER | OUTER | BRIGHTNESS | SPEED | DIRECTION, 23 },
			{ "Twinkle", 	       0x2a, 0x0,  0, INNER | OUTER | BRIGHTNESS | SPEED, 24 },
			{ "Rainbow", 	       0x2b, 0x0,  0, INNER_AND_OUTER | BRIGHTNESS | SPEED | DIRECTION, 25 },
			{ "Color Cycle",       0x2e, 0x0,  4, INNER_AND_OUTER | BRIGHTNESS | SPEED | DIRECTION, 26 },
			{ "Taichi", 	       0x2f, 0x0,  2, INNER_AND_OUTER | BRIGHTNESS | SPEED | DIRECTION, 27 },
			{ "Warning", 	       0x30, 0x0,  4, INNER_AND_OUTER | BRIGHTNESS | SPEED, 28 },
			{ "Voice", 	       0x31, 0x0,  4, INNER_AND_OUTER | BRIGHTNESS | SPEED | DIRECTION, 29 },
			{ "Mixing", 	       0x32, 0x47, 2, INNER_AND_OUTER | MERGE | BRIGHTNESS | SPEED, 30 },
			{ "Tide", 	       0x33, 0x48, 4, INNER_AND_OUTER | MERGE | BRIGHTNESS | SPEED, 31 },
			{ "Scan", 	       0x34, 0x44, 2, INNER_AND_OUTER | MERGE | BRIGHTNESS | SPEED, 32 },
			{ "Contest", 	       0x35, 0x45, 3, INNER_AND_OUTER | MERGE | BRIGHTNESS | SPEED | DIRECTION, 33 },
			{ "Colorful City",     0x38, 0x0,  0, INNER_AND_OUTER | BRIGHTNESS | SPEED, 34 },
			{ "Render", 	       0x39, 0x0,  4, INNER_AND_OUTER | BRIGHTNESS | SPEED | DIRECTION, 35 },
			{ "Twinkle", 	       0x3a, 0x0,  0, INNER_AND_OUTER | BRIGHTNESS | SPEED, 36 },
			{ "Wave", 	       0x3b, 0x49, 1, INNER_AND_OUTER | MERGE | BRIGHTNESS | SPEED, 37 },
			{ "Spring", 	       0x3c, 0x4b, 4, INNER_AND_OUTER | MERGE | BRIGHTNESS | SPEED | DIRECTION, 38 },
			{ "Tail Chasing",      0x3d, 0x4a, 4, INNER_AND_OUTER | MERGE | BRIGHTNESS | SPEED | DIRECTION, 39 },
			{ "Mop Up", 	       0x3e, 0x4c, 2, INNER_AND_OUTER | MERGE | BRIGHTNESS | SPEED, 40 },
			{ "Tornado", 	       0x3f, 0x0,  4, INNER_AND_OUTER | BRIGHTNESS | SPEED | DIRECTION, 41 },
			{ "Staggered", 	       0x40, 0x0,  4, INNER_AND_OUTER | BRIGHTNESS | SPEED, 42 },
			{ "Spanning Teacups",  0x41, 0x0,  4, INNER_AND_OUTER | BRIGHTNESS | SPEED | DIRECTION, 43 },
			{ "Electric Current",  0x42, 0x4f, 4, INNER_AND_OUTER | MERGE | BRIGHTNESS | SPEED, 44 },
			{ "Stack", 	       0x43, 0x0,  2, INNER_AND_OUTER | BRIGHTNESS | SPEED | DIRECTION, 45 },
			/*{ "Scan", 	       0x44, 0x0, 2, MERGE | BRIGHTNESS | SPEED },
 			{ "Contest", 	       0x45, 0x0, 3, MERGE | BRIGHTNESS | SPEED | DIRECTION }, 
			{ "Runway", 	       0x46, 0x0, 2, MERGE | BRIGHTNESS | SPEED },
			{ "Mixing", 	       0x47, 0x0, 2, MERGE | BRIGHTNESS | SPEED },
			{ "Tide", 	       0x48, 0x0, 4, MERGE | BRIGHTNESS | SPEED },
			{ "Wave", 	       0x49, 0x0, 1, MERGE | BRIGHTNESS | SPEED },
			{ "Tail Chasing",      0x4a, 0x0, 4, MERGE | BRIGHTNESS | SPEED | DIRECTION },
			{ "Spring", 	       0x4b, 0x0, 4, MERGE | BRIGHTNESS | SPEED | DIRECTION },
			{ "Mop Up", 	       0x4c, 0x0, 2, MERGE | BRIGHTNESS | SPEED },
			{ "Electric Current",  0x4f, 0x0, 4, MERGE | BRIGHTNESS | SPEED }, */};
