#include "controller.h"

const struct rgb_mode rgb_modes[] = 
		     {  { "Static Color",      0x01, 6, INNER | OUTER }, 
			{ "Breathing",         0x02, 6, INNER | OUTER },
			{ "Rainbow Morph",     0x04, 0, INNER | OUTER },
			{ "Rainbow",           0x05, 0, INNER_OR_OUTER },
			{ "Breathing Rainbow", 0x06, 0, OUTER },
			{ "Meteor Rainbow",    0x08, 0, INNER_OR_OUTER },
			{ "Color Cycle",       0x18, 4, INNER },
			{ "Meteor", 	       0x19, 4, INNER | OUTER | INNER_OR_OUTER },
			{ "Runway", 	       0x1a, 2, INNER | OUTER | INNER_OR_OUTER },
			{ "Mop Up", 	       0x1b, 2, INNER_OR_OUTER },
			{ "Color Cycle",       0x1c, 4, OUTER }, 
			{ "Lottery", 	       0x1d, 2, INNER_OR_OUTER },
			{ "Wave", 	       0x1e, 1, INNER_OR_OUTER }, 
			{ "Spring", 	       0x1f, 4, INNER_OR_OUTER },
			{ "Tail Chasing",      0x20, 4, INNER_OR_OUTER },
			{ "Warning", 	       0x21, 4, INNER_OR_OUTER },
			{ "Voice", 	       0x22, 4, INNER_OR_OUTER },
			{ "Mixing", 	       0x23, 2, INNER_OR_OUTER },
			{ "Stack", 	       0x24, 2, INNER_OR_OUTER },
			{ "Tide", 	       0x25, 4, INNER_OR_OUTER },
			{ "Scan", 	       0x26, 1, INNER_OR_OUTER },
			{ "Pac-Man", 	       0x27, 2, INNER },
			{ "Colorful City",     0x28, 0, INNER_OR_OUTER },
			{ "Render", 	       0x29, 4, INNER_OR_OUTER },
			{ "Twinkle", 	       0x2a, 0, INNER_OR_OUTER },
			{ "Rainbow", 	       0x2b, 0, INNER | OUTER },
			{ "Color Cycle",       0x2e, 4, INNER | OUTER },
			{ "Taichi", 	       0x2f, 2, INNER | OUTER },
			{ "Warning", 	       0x30, 4, INNER | OUTER },
			{ "Voice", 	       0x31, 4, INNER | OUTER },
			{ "Mixing", 	       0x32, 2, INNER | OUTER },
			{ "Tide", 	       0x33, 4, INNER | OUTER },
			{ "Scan", 	       0x34, 2, INNER | OUTER },
			{ "Contest", 	       0x35, 3, INNER | OUTER },
			{ "Colorful City",     0x38, 0, INNER | OUTER },
			{ "Render", 	       0x39, 4, INNER | OUTER },
			{ "Twinkle", 	       0x3a, 0, INNER | OUTER },
			{ "Wave", 	       0x3b, 1, INNER | OUTER },
			{ "Spring", 	       0x3c, 4, INNER | OUTER },
			{ "Tail Chasing",      0x3d, 4, INNER | OUTER },
			{ "Mop Up", 	       0x3e, 2, INNER | OUTER },
			{ "Tornado", 	       0x3f, 4, INNER | OUTER },
			{ "Staggered", 	       0x40, 4, INNER | OUTER },
			{ "Spanning Teacups",  0x41, 4, INNER | OUTER },
			{ "Electric Current",  0x42, 4, INNER | OUTER },
			{ "Stack", 	       0x43, 2, INNER | OUTER },
			{ "Scan", 	       0x44, 2, MERGE },
 			{ "Contest", 	       0x45, 3, MERGE }, 
			{ "Runway", 	       0x46, 2, MERGE },
			{ "Mixing", 	       0x47, 2, MERGE },
			{ "Tide", 	       0x48, 4, MERGE },
			{ "Wave", 	       0x49, 1, MERGE },
			{ "Tail Chasing",      0x4a, 4, MERGE },
			{ "Spring", 	       0x4b, 4, MERGE },
			{ "Mop Up", 	       0x4c, 2, MERGE },
			{ "Electric Current",  0x4f, 4, MERGE }, };
